# Site settings
title:          Wire Postmortems
description:    ""
baseurl:        "https://wireapp.github.io/postmortems"

# Google Analytics
google_analytics: UA-XXXXXXXXX-1 # <-- THIS SHOULD BE YOUR GOOGLE ANALYTICS ID

# Author
author:
  name:         Fernando Cejas
  url:          https://wire.com/
  email:        fernando@wire.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale